package models
import (
"time"
)
type Gdxm struct {
  GD_GUID   	string    	`xorm:" not null VARCHAR(100)"`
  ZD_GUID   	string    	`xorm:"VARCHAR(100)"`
  XZQ_DM    	string    	`xorm:" not null VARCHAR(10)"`
  XM_XH     	float64   	`xorm:"DECIMAL(5,0)"`
  BH        	string    	`xorm:"VARCHAR(100)"`
  DZ_BA_BH  	string    	`xorm:"VARCHAR(100)"`
  XM_MC     	string    	`xorm:"TEXT"`       
  TZZT_XZ   	string    	`xorm:"VARCHAR(10)"`
  HY_FL     	string    	`xorm:"VARCHAR(10)"`
  TD_JB     	string    	`xorm:"VARCHAR(30)"`
  ZD_BH     	string    	`xorm:"VARCHAR(100)"`
  TD_ZL     	string    	`xorm:"VARCHAR(200)"`
  GD_ZMJ    	float64   	`xorm:"DECIMAL(18,6)"`
  GY_FS     	string    	`xorm:"VARCHAR(10)"`
  GY_MJ     	float64   	`xorm:"DECIMAL(18,6)"`
  XZ_MJ     	float64   	`xorm:"DECIMAL(18,6)"`
  TD_YT     	string    	`xorm:"VARCHAR(6)"` 
  CR_NX     	string    	`xorm:"VARCHAR(255)"`
  YT_SM     	string    	`xorm:"VARCHAR(255)"`
  JD_SJ     	time.Time 	`xorm:"DATETIME(6)"`
  JE        	float64   	`xorm:"DECIMAL(20,6)"`
  GDZC_TZE  	float64   	`xorm:"DECIMAL(18,4)"`
  TZ_QD     	float64   	`xorm:"DECIMAL(18,4)"`
  ZT_JZ_XZ  	string    	`xorm:"VARCHAR(255)"`
  FS_JZ_XZ  	string    	`xorm:"VARCHAR(255)"`
  JZ_MJ     	float64   	`xorm:"DECIMAL(18,4)"`
  MIN_JZ_MD 	float64   	`xorm:"DECIMAL(8,2)"`
  MAX_JZ_MD 	float64   	`xorm:"DECIMAL(8,2)"`
  MIN_RJL   	float64   	`xorm:"DECIMAL(8,2)"`
  MAX_RJL   	float64   	`xorm:"DECIMAL(8,2)"`
  MIN_LHL   	float64   	`xorm:"DECIMAL(8,2)"`
  MAX_LHL   	float64   	`xorm:"DECIMAL(8,2)"`
  MIN_JZ_GD 	float64   	`xorm:"DECIMAL(8,2)"`
  MAX_JZ_GD 	float64   	`xorm:"DECIMAL(8,2)"`
  QT_TD_YQ  	string    	`xorm:"TEXT"`       
  DG_SJ     	time.Time 	`xorm:"DATETIME(6)"`
  JG_SJ     	time.Time 	`xorm:"DATETIME(6)"`
  KFJS_QX   	float64   	`xorm:"DECIMAL(8,2)"`
  QD_RQ     	time.Time 	`xorm:"DATETIME(6)"`
  PZ_WH     	string    	`xorm:"VARCHAR(100)"`
  PZ_RQ     	time.Time 	`xorm:"DATETIME(6)"`
  PZ_JG     	string    	`xorm:"VARCHAR(100)"`
  ZBX_LX    	string    	`xorm:"VARCHAR(50)"`
  ZBX_TYLX  	string    	`xorm:"VARCHAR(50)"`
  ZBX_JD    	float64   	`xorm:"DECIMAL(18,4)"`
  SB_CS     	float64   	`xorm:"DECIMAL(5,0)"`
  SBR       	string    	`xorm:"VARCHAR(50)"`
  SB_SJ     	time.Time 	`xorm:"DATETIME(6)"`
  SB_XZQ    	string    	`xorm:"VARCHAR(9)"` 
  XM_CJ     	float64   	`xorm:" not null DECIMAL(5,0)"`
  XM_ZT     	string    	`xorm:" not null VARCHAR(10)"`
  OLD_GD_GUID	string    	`xorm:"VARCHAR(50)"`
  KFTZ_ZE   	float64   	`xorm:"DECIMAL(18,3)"`
  CREATE_DATE	time.Time 	`xorm:"DATETIME(6)"`
  DELETE_DATE	time.Time 	`xorm:"DATETIME(6)"`
  CREATE_USER	string    	`xorm:"VARCHAR(50)"`
  BG_JD_SJ  	time.Time 	`xorm:"DATETIME(6)"`
  BG_DG_SJ  	time.Time 	`xorm:"DATETIME(6)"`
  BG_JG_SJ  	time.Time 	`xorm:"DATETIME(6)"`
  TB_ZT     	float64   	`xorm:"DECIMAL(10,0)"`
  ZD_SZ_QY  	string    	`xorm:"VARCHAR(50)"`
  CL_XZCR_MJ	float64   	`xorm:"DECIMAL(18,6)"`
  CL_GBXZCR_MJ	float64   	`xorm:"DECIMAL(18,6)"`
  CL_QT_MJ  	float64   	`xorm:"DECIMAL(18,6)"`
  PC_MJ     	float64   	`xorm:"DECIMAL(18,6)"`
  MODIFY_DATE	time.Time 	`xorm:"DATETIME(6)"`
  GY_WLD_MJ 	float64   	`xorm:"DECIMAL(18,6)"`
  WL_BZ     	string    	`xorm:"VARCHAR(2)"` 
  CH_SJ     	time.Time 	`xorm:"DATETIME(6)"`
  CL_XQ     	float64   	`xorm:"DECIMAL(18,6)"`
  CL_MJ     	float64   	`xorm:"DECIMAL(18,6)"`
  HT_LX     	string    	`xorm:"VARCHAR(10)"`
  BZ        	string    	`xorm:"TEXT"`       
  PARAID    	float64   	`xorm:" not null DECIMAL(2,0)"`
  KFLY_BZ   	string    	`xorm:"VARCHAR(5)"` 
  WKFLY_YY  	string    	`xorm:"TEXT"`       
  SJ_JD_SJ  	time.Time 	`xorm:"DATETIME(6)"`
  SJ_DG_SJ  	time.Time 	`xorm:"DATETIME(6)"`
  SJ_JG_SJ  	time.Time 	`xorm:"DATETIME(6)"`
  SF_SH     	float64   	`xorm:"DECIMAL(10,0)"`
  XZ_ZT     	float64   	`xorm:"DECIMAL(10,0)"`
  QY_SS_LX  	string    	`xorm:"VARCHAR(50)"`
  LSXZ_ZT   	float64   	`xorm:"DECIMAL(10,0)"`
  HAVE_JZD  	float64   	`xorm:"DECIMAL(10,0)"`
  SRR       	string    	`xorm:"TEXT"`       
  CX_YY     	string    	`xorm:"TEXT"`       
  MIN_JZ_MD_TAG	string    	`xorm:"VARCHAR(2)"` 
  MAX_JZ_MD_TAG	string    	`xorm:"VARCHAR(2)"` 
  MIN_RJL_TAG	string    	`xorm:"VARCHAR(2)"` 
  MAX_RJL_TAG	string    	`xorm:"VARCHAR(2)"` 
  MIN_LHL_TAG	string    	`xorm:"VARCHAR(2)"` 
  MAX_LHL_TAG	string    	`xorm:"VARCHAR(2)"` 
  MIN_JZ_GD_TAG	string    	`xorm:"VARCHAR(2)"` 
  MAX_JZ_GD_TAG	string    	`xorm:"VARCHAR(2)"` 
  JD_SJ1    	time.Time 	`xorm:"DATETIME(6)"`
  DG_SJ1    	time.Time 	`xorm:"DATETIME(6)"`
  JG_SJ1    	time.Time 	`xorm:"DATETIME(6)"`
  ZJGG_MJ   	float64   	`xorm:"DECIMAL(18,6)"`
  SH_ZT     	float64   	`xorm:"DECIMAL(10,0)"`
  SH_YJ     	string    	`xorm:"TEXT"`       
  CQ_TS     	float64   	`xorm:"DECIMAL(10,0)"`
  SC_SB_SJ  	time.Time 	`xorm:"DATETIME(6)"`
  BGQ_QD_RQ 	time.Time 	`xorm:"DATETIME(6)"`
  BG_YY     	string    	`xorm:"TEXT"`       
  IS_STOP   	string    	`xorm:"VARCHAR(10)"`
  GKFQDJX_MJ	float64   	`xorm:"DECIMAL(18,6)"`
  WLYDJX_MJ 	float64   	`xorm:"DECIMAL(18,6)"`
  TG_SJ     	time.Time 	`xorm:"DATETIME(6)"`
  GJBG_BAH  	string    	`xorm:"TEXT"`       
  HAVE_BAH  	float64   	`xorm:"DECIMAL(10,0)"`
  BAH_WJMC  	string    	`xorm:"TEXT"`       
  BAH_WH    	string    	`xorm:"TEXT"`       
  BAH_BDJKBZ	string    	`xorm:"TEXT"`       
  W_CYZC_SM 	string    	`xorm:"TEXT"`       
  CYZC_GUID 	string    	`xorm:"TEXT"`       
  CYZC_WH   	string    	`xorm:"TEXT"`       
}